const {test,expect}=require('@playwright/test');
const {setup,profile,mentor,request,PEER}=require('./mentorship-fixture.cjs');
const nav=async(page,name)=>page.getByRole('navigation').getByRole('button',{name,exact:true}).click();
const explore=async page=>{await nav(page,'Descobrir');await expect(page.getByRole('heading',{name:'Ana Oliveira',exact:true})).toBeVisible();};
test('explains matches and combines persisted discovery filters',async({page})=>{
 const {db}=await setup(page,{own:profile({catalog_course_id:'engenharia',availability_slots:['seg-noite']}),mentors:[mentor({catalog_course_id:'engenharia',availability_slots:['seg-noite']})]});await explore(page);
 await expect(page.getByRole('region',{name:'Por que este perfil?'})).toHaveCount(0);await page.locator('.card-compatibility summary').click();
 await expect(page.getByRole('region',{name:'Por que este perfil?'})).toContainText('Pode ajudar em Cálculo');await expect(page.getByRole('region',{name:'Por que este perfil?'})).toContainText('Horário em comum');
 await page.getByText('Refinar descoberta',{exact:true}).click();await page.getByLabel('Curso do estudante').selectOption('engenharia');await page.getByLabel('Semestre do estudante').selectOption('6');await page.getByLabel('Formato do encontro').selectOption('online');await page.getByLabel('Horário habitual',{exact:true}).selectOption('seg-noite');await page.getByRole('button',{name:'Aplicar filtros'}).click();
 await expect(page.getByRole('heading',{name:'Ana Oliveira',exact:true})).toBeVisible();expect(db.calls.filter(c=>c.name==='mentor_discover_product').at(-1).body).toMatchObject({p_course_id:'engenharia',p_semester:6,p_format:'online',p_slot:'seg-noite'});
 await page.getByLabel('Semestre do estudante').selectOption('1');await page.getByRole('button',{name:'Aplicar filtros'}).click();await expect(page.getByRole('heading',{name:'Novos aprendizados vêm aí.'})).toBeVisible();await page.getByRole('button',{name:'Limpar busca e filtros'}).first().click();await expect(page.getByRole('heading',{name:'Ana Oliveira',exact:true})).toBeVisible();
});
test('favorites are persistent through reload, removable and never a contact bypass',async({page})=>{
 const {db}=await setup(page);await explore(page);await page.getByRole('button',{name:'Salvar nos favoritos: Ana Oliveira'}).click();await expect(page.getByRole('button',{name:'Remover dos favoritos: Ana Oliveira'})).toHaveAttribute('aria-pressed','true');expect(db.mentors[0].is_favorite).toBe(true);
 await page.getByRole('button',{name:'Perfis salvos',exact:true}).click();await expect(page.getByRole('heading',{name:'Perfis salvos',exact:true})).toBeVisible();await page.getByRole('button',{name:'Ver perfil',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Experiência declarada');await page.getByRole('button',{name:'Fechar janela'}).click();
 await page.reload();await explore(page);await expect(page.getByRole('button',{name:'Remover dos favoritos: Ana Oliveira'})).toBeVisible();await page.getByRole('button',{name:'Perfis salvos',exact:true}).click();await page.getByRole('button',{name:'Remover dos favoritos: Ana Oliveira'}).click();await expect(page.getByRole('heading',{name:'Um bom perfil merece ser lembrado.'})).toBeVisible();
});
test('rich profile saves methodology experience and structured slots without losing catalog selections',async({page})=>{
 const {db}=await setup(page);await nav(page,'Perfil');await page.getByText('Como você ajuda e quando pode estudar (opcional)',{exact:true}).click();await page.getByLabel('Como gosto de explicar').fill('Exemplos práticos e exercícios acompanhados.');await page.getByLabel('Minha experiência com a matéria').fill('Cursei cálculo e organizo um grupo de estudos.');await page.getByRole('checkbox',{name:'Segunda · noite',exact:true}).check();await page.getByRole('button',{name:'Salvar perfil',exact:true}).click();await expect(page.getByRole('heading',{name:'Bem-vindo de volta',exact:true})).toBeVisible();expect(db.own).toMatchObject({availability_slots:['seg-noite'],methodology:'Exemplos práticos e exercícios acompanhados.',learning_subjects:['Cálculo']});
 await nav(page,'Perfil');await page.getByText('Como você ajuda e quando pode estudar (opcional)',{exact:true}).click();await expect(page.getByRole('checkbox',{name:'Segunda · noite',exact:true})).toBeChecked();
});
test('guided requests reject empty context and show the recipient the exact persisted proposal',async({page})=>{
 const {db}=await setup(page);await explore(page);await page.getByRole('button',{name:'Solicitar monitoria',exact:true}).click();await page.getByLabel('Em qual disciplina?').selectOption('Cálculo');await page.getByRole('button',{name:'Confirmar solicitação'}).click();expect(db.requests).toHaveLength(0);
 await page.getByLabel('Qual é sua dúvida?').fill('Como calcular o limite desta função?');await page.getByLabel('O que você quer conseguir?').fill('Resolver exercícios de limites.');await page.getByRole('button',{name:'Confirmar solicitação'}).click();await page.getByText('Contexto do pedido',{exact:true}).click();await expect(page.locator('#requestList')).toContainText('Como calcular o limite desta função?');expect(db.requests[0]).toMatchObject({question:'Como calcular o limite desta função?',objective:'Resolver exercícios de limites.',proposed_at:null});
 db.requests[0].direction='incoming';await page.getByRole('button',{name:'Recebidas (1)'}).click();await page.getByText('Contexto do pedido',{exact:true}).click();await expect(page.locator('#requestList')).toContainText('Resolver exercícios de limites.');
});
test('reports preserve text on error and are privately trackable without a moderator panel',async({page})=>{
 const {db}=await setup(page,{errors:{mentor_report:{message:'Network error'}}});await explore(page);await page.getByRole('button',{name:'Ver perfil',exact:false}).click();await page.getByRole('button',{name:'Denunciar estudante',exact:true}).click();await page.getByLabel('Motivo da denúncia').selectOption('spam');await page.getByLabel('O que aconteceu?').fill('Recebi mensagens de propaganda repetidamente.');await page.getByRole('button',{name:'Enviar denúncia'}).click();await expect(page.getByRole('alert')).toContainText('Confira sua conexão');await expect(page.getByLabel('O que aconteceu?')).toHaveValue('Recebi mensagens de propaganda repetidamente.');delete db.errors.mentor_report;await page.getByRole('button',{name:'Enviar denúncia'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await nav(page,'Perfil');await page.getByRole('button',{name:'Segurança e denúncias',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('Em análise');await expect(page.getByRole('button',{name:'Abrir painel de moderação'})).toHaveCount(0);
});
test('authorized moderation UI sends confirmed decisions with a justification',async({page})=>{
 const {db}=await setup(page,{db:{moderator:true,addonResponses:{mentor_moderation_queue:[{id:PEER,target_name:'Ana Oliveira',reporter_name:'Estudante',reason:'spam',details:'Propaganda repetida.'}]}}});await nav(page,'Perfil');await page.getByRole('button',{name:'Segurança e denúncias',exact:true}).click();await page.getByRole('button',{name:'Abrir painel de moderação'}).click();await expect(page.getByRole('dialog')).toContainText('Propaganda repetida.');await page.getByLabel('Ação sobre o acesso').selectOption('restrict');await page.getByLabel('Justificativa da análise').fill('Propaganda reiterada após análise do relato.');await page.getByRole('checkbox',{name:'Revisei o relato e confirmo esta decisão.'}).check();await page.getByRole('button',{name:'Registrar decisão'}).click();await expect.poll(()=>db.calls.filter(c=>c.name==='mentor_moderate').length).toBe(1);expect(db.calls.find(c=>c.name==='mentor_moderate').body).toMatchObject({p_action:'restrict',p_status:'reviewed'});
});
test('product content escapes untrusted profile and request text',async({page})=>{
 const attack='<img src=x onerror="window.pwned=1">';await setup(page,{mentors:[mentor({methodology:attack,experience:attack})],requests:[request({question:attack,objective:attack})]});await explore(page);await page.getByRole('button',{name:'Ver perfil',exact:false}).click();await expect(page.getByRole('dialog')).toContainText(attack);await expect(page.getByRole('dialog').locator('img')).toHaveCount(0);expect(await page.evaluate(()=>window.pwned)).toBeUndefined();
});
